// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCMS_Backend.Data;

#nullable disable

namespace PCMS_Backend.Migrations
{
    [DbContext(typeof(PcmsDbContext))]
    [Migration("20260624133019_CoverageGapAlertTable")]
    partial class CoverageGapAlertTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCMS_Backend.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityRecordId")
                        .HasColumnType("int");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageAssignment", b =>
                {
                    b.Property<int>("CoverageAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageAssignmentId"));

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("CoverageDate")
                        .HasColumnType("date");

                    b.Property<int>("CoverageScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("CoverageAssignmentId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("PhysicianId", "CoverageDate");

                    b.HasIndex("CoverageScheduleId", "CoverageDate", "SpecialtyId", "ShiftType")
                        .IsUnique();

                    b.ToTable("CoverageAssignments");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageGapAlert", b =>
                {
                    b.Property<int>("CoverageGapAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageGapAlertId"));

                    b.Property<string>("AlertReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AlertStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CoverageAssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RequestedByPhysicianId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CoverageGapAlertId");

                    b.HasIndex("AlertStatus");

                    b.HasIndex("CoverageAssignmentId");

                    b.HasIndex("RequestedByPhysicianId");

                    b.ToTable("CoverageGapAlerts");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageSchedule", b =>
                {
                    b.Property<int>("CoverageScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("CoverageScheduleId");

                    b.HasIndex("PublishedByUserId");

                    b.ToTable("CoverageSchedules");
                });

            modelBuilder.Entity("PCMS_Backend.Models.ExternalLeavesData", b =>
                {
                    b.Property<int>("ExternalLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalLeaveId"));

                    b.Property<DateOnly>("LeaveEndDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("LeaveStartDate")
                        .HasColumnType("date");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.HasKey("ExternalLeaveId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("ExternalLeavesData");
                });

            modelBuilder.Entity("PCMS_Backend.Models.ExternalShiftsData", b =>
                {
                    b.Property<int>("ExternalShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalShiftId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ExternalShiftId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("ExternalShiftsData");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicianCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PhysicianId");

                    b.HasIndex("MedicalLicenseNumber")
                        .IsUnique();

                    b.HasIndex("PhysicianCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Physicians");
                });

            modelBuilder.Entity("PCMS_Backend.Models.PhysicianSpecialtyMap", b =>
                {
                    b.Property<int>("PhysicianSpecialtyMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianSpecialtyMapId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsPrimarySpecialty")
                        .HasColumnType("bit");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("PhysicianSpecialtyMapId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("PhysicianId", "SpecialtyId")
                        .IsUnique();

                    b.ToTable("PhysicianSpecialtyMaps");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "House Supervisor"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Physician"
                        });
                });

            modelBuilder.Entity("PCMS_Backend.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecialtyId");

                    b.HasIndex("SpecialtyName")
                        .IsUnique();

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Cardiology"
                        },
                        new
                        {
                            SpecialtyId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Neurology"
                        },
                        new
                        {
                            SpecialtyId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Orthopedics"
                        },
                        new
                        {
                            SpecialtyId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Emergency Medicine"
                        },
                        new
                        {
                            SpecialtyId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Radiology"
                        },
                        new
                        {
                            SpecialtyId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "Anesthesiology"
                        },
                        new
                        {
                            SpecialtyId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SpecialtyName = "General Surgery"
                        });
                });

            modelBuilder.Entity("PCMS_Backend.Models.SwapRequest", b =>
                {
                    b.Property<int>("SwapRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwapRequestId"));

                    b.Property<int>("CoverageAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("RequestComments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RequestedByPhysicianId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("TargetPhysicianId")
                        .HasColumnType("int");

                    b.HasKey("SwapRequestId");

                    b.HasIndex("CoverageAssignmentId");

                    b.HasIndex("RequestedByPhysicianId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TargetPhysicianId");

                    b.ToTable("SwapRequests");
                });

            modelBuilder.Entity("PCMS_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PCMS_Backend.Models.AuditLog", b =>
                {
                    b.HasOne("PCMS_Backend.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageAssignment", b =>
                {
                    b.HasOne("PCMS_Backend.Models.CoverageSchedule", "CoverageSchedule")
                        .WithMany("CoverageAssignments")
                        .HasForeignKey("CoverageScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.Physician", "Physician")
                        .WithMany("CoverageAssignments")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.Specialty", "Specialty")
                        .WithMany("CoverageAssignments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverageSchedule");

                    b.Navigation("Physician");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageGapAlert", b =>
                {
                    b.HasOne("PCMS_Backend.Models.CoverageAssignment", "CoverageAssignment")
                        .WithMany("CoverageGapAlerts")
                        .HasForeignKey("CoverageAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.Physician", "Physician")
                        .WithMany("CoverageGapAlert")
                        .HasForeignKey("RequestedByPhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageAssignment");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageSchedule", b =>
                {
                    b.HasOne("PCMS_Backend.Models.User", "PublishedByUser")
                        .WithMany("PublishedSchedules")
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("PCMS_Backend.Models.ExternalLeavesData", b =>
                {
                    b.HasOne("PCMS_Backend.Models.Physician", "Physician")
                        .WithMany("ExternalLeavesData")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("PCMS_Backend.Models.ExternalShiftsData", b =>
                {
                    b.HasOne("PCMS_Backend.Models.Physician", "Physician")
                        .WithMany("ExternalShiftsData")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Notification", b =>
                {
                    b.HasOne("PCMS_Backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Physician", b =>
                {
                    b.HasOne("PCMS_Backend.Models.User", "User")
                        .WithOne("Physician")
                        .HasForeignKey("PCMS_Backend.Models.Physician", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PCMS_Backend.Models.PhysicianSpecialtyMap", b =>
                {
                    b.HasOne("PCMS_Backend.Models.Physician", "Physician")
                        .WithMany("PhysicianSpecialtyMaps")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.Specialty", "Specialty")
                        .WithMany("PhysicianSpecialtyMaps")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physician");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("PCMS_Backend.Models.SwapRequest", b =>
                {
                    b.HasOne("PCMS_Backend.Models.CoverageAssignment", "CoverageAssignment")
                        .WithMany("SwapRequests")
                        .HasForeignKey("CoverageAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.Physician", "RequestedByPhysician")
                        .WithMany("RequestedSwapRequests")
                        .HasForeignKey("RequestedByPhysicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PCMS_Backend.Models.User", "ReviewedByUser")
                        .WithMany("ReviewedSwapRequests")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PCMS_Backend.Models.Physician", "TargetPhysician")
                        .WithMany("TargetSwapRequests")
                        .HasForeignKey("TargetPhysicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverageAssignment");

                    b.Navigation("RequestedByPhysician");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("TargetPhysician");
                });

            modelBuilder.Entity("PCMS_Backend.Models.User", b =>
                {
                    b.HasOne("PCMS_Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageAssignment", b =>
                {
                    b.Navigation("CoverageGapAlerts");

                    b.Navigation("SwapRequests");
                });

            modelBuilder.Entity("PCMS_Backend.Models.CoverageSchedule", b =>
                {
                    b.Navigation("CoverageAssignments");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Physician", b =>
                {
                    b.Navigation("CoverageAssignments");

                    b.Navigation("CoverageGapAlert");

                    b.Navigation("ExternalLeavesData");

                    b.Navigation("ExternalShiftsData");

                    b.Navigation("PhysicianSpecialtyMaps");

                    b.Navigation("RequestedSwapRequests");

                    b.Navigation("TargetSwapRequests");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PCMS_Backend.Models.Specialty", b =>
                {
                    b.Navigation("CoverageAssignments");

                    b.Navigation("PhysicianSpecialtyMaps");
                });

            modelBuilder.Entity("PCMS_Backend.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Physician");

                    b.Navigation("PublishedSchedules");

                    b.Navigation("ReviewedSwapRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
